### ISSUE TITLE
inicialização

### ISSUE THREAD

**Issue by davi23code** [jeancabral/react-pdv#6]
olá, Jean. instalei o  react pdv mas quando abri não aparece todas as funcionalidades , fiquei em dúvida se houve algum erro na instalação ou se o projeto ainda esta em construção.

**Comment by cgarrotti** [comment]
ta incompleto amigo, ja olhei os fontes aqui tb

**Comment by jeancabral** [comment]
Fala @davi23code @cgarrotti tudo bem? Estou retornando com o projeto. Estarei adicionando um Rest API ao projeto nos próximos dias.
